[build]
  command = "npm run build"
  publish = "_site"

[functions]
  directory = "netlify/functions"

[build.processing]
  skip_processing = true

[build.optimization]
  bundle = true
  minify = true